{"uuid": "0d1d884c-28fc-468a-889c-2d8c66346dfb", "children": ["5a61cfb2-aee8-40a8-b425-b10568e76202"], "befores": [{"name": "browser", "status": "passed", "start": 1605333938169, "stop": 1605333941591}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.198)\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/hongmeisun/Desktop/shmcode/lemon/conftest.py\", line 30, in browser\n    driver.close()\n  File \"/Users/hongmeisun/Library/Python/3.6/lib/python/site-packages/selenium/webdriver/remote/webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/hongmeisun/Library/Python/3.6/lib/python/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/hongmeisun/Library/Python/3.6/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1605333961588, "stop": 1605333961593}], "start": 1605333938169, "stop": 1605333961593}