{"uuid": "f08a382b-1091-441e-9142-232b41c1be0d", "children": ["b02a2147-8a2c-45cb-8be3-8ba34d37e63f", "5638a2e2-7cb6-4e39-a26b-80bdf39a72f3", "80c3e0a1-c098-4af1-a44d-485739d24bba", "828ee243-5a15-4175-a999-3c1c2179f753", "f188e052-15e8-49e3-8e87-1f7535f6083c"], "befores": [{"name": "browser", "status": "passed", "start": 1605333982835, "stop": 1605333986213}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=86.0.4240.198)\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/hongmeisun/Desktop/shmcode/lemon/conftest.py\", line 30, in browser\n    driver.close()\n  File \"/Users/hongmeisun/Library/Python/3.6/lib/python/site-packages/selenium/webdriver/remote/webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/hongmeisun/Library/Python/3.6/lib/python/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/hongmeisun/Library/Python/3.6/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1605334007175, "stop": 1605334007181}], "start": 1605333982835, "stop": 1605334007181}